version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: maslyakbank_database
    restart: always
    environment:
      POSTGRES_USER: Maslyak
      POSTGRES_PASSWORD: LaLa27418182!
      POSTGRES_DB: postgres
    ports:
      - "7777:5432"
    networks:
      - MaslyakBankNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Maslyak -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
      image: redis:latest
      restart: always
      ports:
        - "6666:6379"
      networks:
        - MaslyakBankNetwork
      volumes:
        - /path/to/local/d–∞ta:/root/redis
        - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf


networks:
  MaslyakBankNetwork:
      external: true
