services:
  spring_app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: maslyakbank_token
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1230:8080"
    networks:
      - MaslyakBankNetwork

networks:
  MaslyakBankNetwork:
    external: true

