services:
  spring_app:
    build: ..
    container_name: maslyakbank_token
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1230:8080"
    env_file:
      - ../.env
    networks:
      - MaslyakBankNetwork

networks:
  MaslyakBankNetwork:
    external: true

