version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: maslyakbank_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "7777:5432"
    networks:
      - MaslyakBankNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  liquibase-cli:
    build:
      context: .
      dockerfile: liquibase-docker/Dockerfile
    container_name: maslyakbank_liquibase
    depends_on:
      db:
        condition: service_healthy
    networks:
      - MaslyakBankNetwork
    volumes:
      - ./MaslyakBank_Infrastructure/liquibase-docker:/liquibase
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6666:6379"
    networks:
      - MaslyakBankNetwork
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  MaslyakBankNetwork:
    external: true
