name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    strategy: # Стратегия для сборки и тестирования
      matrix:
        service:
          - name: Transaction
            docker: transaction
          - name: Token
            docker: token
          - name: Core
            docker: core
          - name: Account
            docker: account

    steps:
      # --- 1. Клонируем репозиторий ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 2. Настраиваем JDK 21 ---
      - name: Set up JDK 21
        uses: ./.github/workflows/actions/setup-jdk

      # --- 3. Сборка и Docker для Services ---
      - name: Build and dockerize services
        run: |
          mvn -B clean package -DskipTests -f MaslyakBank_${{ matrix.service.name }}/pom.xml
          docker build -t maslyakbank-${{ matrix.service.docker }} -f MaslyakBank_${{ matrix.service.name }}/Dockerfile MaslyakBank_${{ matrix.service.name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: maslyakbank-${{ matrix.service.docker }}-jar
          path: MaslyakBank_${{ matrix.service.name }}/target/*.jar
  # --- Шаг 2: Запуск тестов ---
  test:
    runs-on: ubuntu-latest
    needs: build-and-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./.github/workflows/actions/setup-jdk

      - name: Run all tests
        run: mvn -B test

  # --- Шаг 3: Деплой через Docker Compose ---
  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service:
          - name: Transaction
            docker: transaction
          - name: Token
            docker: token
          - name: Core
            docker: core
          - name: Account
            docker: account
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./.github/workflows/actions/setup-jdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create MaslyakBankNetwork || true

      # --- Запуск сервисов через Docker Compose ---
      - name: Start services
        run: docker compose -f MaslyakBank_${{matrix.service.name}}/compose-${{matrix.service.docker}}.yaml up -d
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

